/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "home": [],
    "recipients.index": [],
    "recipients.store": [],
    "recipients.update": [
        {
            "name": "recipient",
            "required": true,
            "binding": "id"
        }
    ],
    "recipients.destroy": [
        {
            "name": "recipient",
            "required": true,
            "binding": "id"
        }
    ],
    "recipients.import": [],
    "email-templates.index": [],
    "email-templates.store": [],
    "email-templates.update": [
        {
            "name": "email_template",
            "required": true
        }
    ],
    "email-templates.destroy": [
        {
            "name": "email_template",
            "required": true
        }
    ],
    "email-templates.send-test": [
        {
            "name": "emailTemplate",
            "required": true,
            "binding": "id"
        }
    ],
    "campaigns.index": [],
    "campaigns.create": [],
    "campaigns.store": [],
    "campaigns.show": [
        {
            "name": "campaign",
            "required": true,
            "binding": "id"
        }
    ],
    "campaigns.update": [
        {
            "name": "campaign",
            "required": true,
            "binding": "id"
        }
    ],
    "campaigns.destroy": [
        {
            "name": "campaign",
            "required": true,
            "binding": "id"
        }
    ],
    "campaigns.edit": [
        {
            "name": "campaign",
            "required": true,
            "binding": "id"
        }
    ],
    "campaigns.send": [
        {
            "name": "campaign",
            "required": true,
            "binding": "id"
        }
    ],
    "campaigns.cancel": [
        {
            "name": "campaign",
            "required": true,
            "binding": "id"
        }
    ],
    "campaigns.track-open": [
        {
            "name": "campaign",
            "required": true,
            "binding": "id"
        },
        {
            "name": "recipient",
            "required": true,
            "binding": "id"
        }
    ],
    "campaigns.track-click": [
        {
            "name": "campaign",
            "required": true,
            "binding": "id"
        },
        {
            "name": "recipient",
            "required": true,
            "binding": "id"
        }
    ],
    "form-templates.index": [],
    "form-templates.store": [],
    "form-templates.show": [
        {
            "name": "form_template",
            "required": true
        }
    ],
    "form-templates.update": [
        {
            "name": "form_template",
            "required": true
        }
    ],
    "form-templates.destroy": [
        {
            "name": "form_template",
            "required": true
        }
    ],
    "form-templates.preview": [
        {
            "name": "formTemplate",
            "required": true,
            "binding": "id"
        }
    ],
    "form-templates.toggle-status": [
        {
            "name": "formTemplate",
            "required": true,
            "binding": "id"
        }
    ],
    "form-templates.duplicate": [
        {
            "name": "formTemplate",
            "required": true,
            "binding": "id"
        }
    ],
    "public.phishing-page": [
        {
            "name": "template",
            "required": true,
            "binding": "id"
        },
        {
            "name": "token",
            "required": true
        }
    ],
    "public.capture-submission": [
        {
            "name": "template",
            "required": true,
            "binding": "id"
        }
    ],
    "public.acknowledge-awareness": [
        {
            "name": "submission",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
